const legalServices = document.querySelector('.legal-services');
const corporateTitle = document.querySelector('.corporate-title');
const legalSupport = document.querySelector('.legal-support');
const compliance = document.querySelector('.compliance');
const drafting = document.querySelector('.drafting');
const loan = document.querySelector('.loan');
const immigrationTitle = document.querySelector('.immigration-title');
const visa = document.querySelector('.visa');
const paperwork = document.querySelector('.paperwork');
const taxTitle = document.querySelector('.tax-title');
const taxation = document.querySelector('.taxation');
const obligation = document.querySelector('.obligation');
const authorities = document.querySelector('.authorities');
const realEstate = document.querySelector('.real-estate');
const contracts = document.querySelector('.contracts');
const estate = document.querySelector('.estate');
const communication = document.querySelector('.communication');
const resolution = document.querySelector('.resolution');
const mediation = document.querySelector('.mediation');
const debt = document.querySelector('.debt');
const civil = document.querySelector('.civil');
const language = localStorage.getItem('language') || 'srb';


getLanguage();
function getLanguage() {
    switch (language) {
        case 'en':
            legalServices.textContent = 'Legal Services';
            corporateTitle.textContent = 'Corporate & Business Law';
            legalSupport.textContent = 'Legal support during regular business activity';
            compliance.textContent = 'Compliance with Serbian tax law and business registration';
            drafting.textContent = 'Drafting contracts and managing shareholder agreements';
            loan.textContent = 'Loan, lease, and purchase/sale contracts';
            immigrationTitle.textContent = 'Immigration & Citizenship Law';
            visa.textContent = 'Visa applications, work permits, and citizenship processes';
            paperwork.textContent = 'Complete paperwork and legal execution';
            taxTitle.textContent = 'Tax & Financial Law';
            taxation.textContent = 'Advising on double taxation, tax deductions';
            obligation.textContent = 'Settled tax obligation certificates';
            authorities.textContent = 'Representation before tax authorities';
            realEstate.textContent = 'Real Estate Law';
            contracts.textContent = 'Property contracts, pre-contracts, and registrations';
            estate.textContent = 'Real estate restructuring and compliance';
            communication.textContent = 'Communication with cadastre and state bodies';
            resolution.textContent = 'Dispute Resolution & Litigation';
            mediation.textContent = 'Mediation before Chamber of Commerce';
            debt.textContent = 'Enforcement procedures and debt recovery';
            civil.textContent = 'Representation in civil, criminal, and executive proceedings';
            return;
        case 'ru':
            legalServices.textContent = 'Юридические услуги';
            corporateTitle.textContent = 'Корпоративное и коммерческое право';
            legalSupport.textContent = 'Юридическая поддержка в ходе обычной хозяйственной деятельности';
            compliance.textContent = 'Соблюдение налогового законодательства Сербии и регистрация бизнеса';
            drafting.textContent = 'Составление контрактов и управление акционерными соглашениями';
            loan.textContent = 'Договоры займа, аренды и купли-продажи';
            immigrationTitle.textContent = 'Закон об иммиграции и гражданстве';
            visa.textContent = 'Заявления на получение визы, разрешения на работу и процессы получения гражданства';
            paperwork.textContent = 'Полная документация и юридическое оформление';
            taxTitle.textContent = 'Налоговое и финансовое право';
            taxation.textContent = 'Консультирование по вопросам двойного налогообложения, налоговых вычетов';
            obligation.textContent = 'Сертификаты об урегулировании налоговых обязательств';
            authorities.textContent = 'Представительство в налоговых органах';
            realEstate.textContent = 'Закон о недвижимости';
            contracts.textContent = 'Договоры купли-продажи недвижимости, предварительные договоры и регистрации';
            estate.textContent = 'Реструктуризация недвижимости и соответствие требованиям';
            communication.textContent = 'Связь с кадастровыми и государственными органами';
            resolution.textContent = 'Разрешение споров и судебные разбирательства';
            mediation.textContent = 'Медиация в Торговой палате';
            debt.textContent = 'Процедуры принудительного исполнения и взыскание задолженности';
            civil.textContent = 'Представительство в гражданском, уголовном и исполнительном производстве';
            return;
        case 'fr':
            legalServices.textContent = 'Services juridiques';
            corporateTitle.textContent = 'Droit des sociétés et des affaires';
            legalSupport.textContent = `Assistance juridique dans le cadre de l'activité commerciale régulière`;
            compliance.textContent = 'Conformité à la législation fiscale serbe et enregistrement des entreprises';
            drafting.textContent = `Rédaction de contrats et gestion de pactes d'actionnaires`;
            loan.textContent = `Contrats de prêt, de location et d'achat/vente`;
            immigrationTitle.textContent = `Droit de l'immigration et de la citoyenneté`;
            visa.textContent = 'Demandes de visa, permis de travail et processus de citoyenneté';
            paperwork.textContent = 'Formalités administratives complètes et exécution légale';
            taxTitle.textContent = 'Droit fiscal et financier';
            taxation.textContent = 'Conseils sur la double imposition et les déductions fiscales';
            obligation.textContent = `Certificats d'obligation fiscale réglés`;
            authorities.textContent = 'Représentation devant les autorités fiscales';
            realEstate.textContent = 'Droit immobilier';
            contracts.textContent = 'Contrats de propriété, précontrats et enregistrements';
            estate.textContent = 'Restructuration et conformité immobilière';
            communication.textContent = `Communication avec le cadastre et les organismes de l'État`;
            resolution.textContent = 'Résolution des litiges et contentieux';
            mediation.textContent = 'Médiation devant la Chambre de commerce';
            debt.textContent = `Procédures d'exécution et recouvrement de créances`;
            civil.textContent = 'Représentation dans les procédures civiles, pénales et exécutives';
            return;
        case 'srb':
            legalServices.textContent = 'Правне услуге';
            corporateTitle.textContent = 'Корпоративно и пословно право';
            legalSupport.textContent = 'Правна подршка током редовних пословних активности';
            compliance.textContent = 'Усклађеност са српским пореским законима и регистрација предузећа';
            drafting.textContent = 'Израда уговора и управљање акционарским споразумима';
            loan.textContent = 'Уговори о зајму, закупу и купопродаји';
            immigrationTitle.textContent = 'Закон о имиграцији и држављанству';
            visa.textContent = 'Захтеви за визе, радне дозволе и поступци за добијање држављанства';
            paperwork.textContent = 'Комплетна папирологија и правно извршење';
            taxTitle.textContent = 'Пореско и финансијско право';
            taxation.textContent = 'Саветовање о двоструком опорезивању, пореским одбитцима';
            obligation.textContent = 'Потврде о измиреним пореским обавезама';
            authorities.textContent = 'Заступање пред пореским органима';
            realEstate.textContent = 'Закон о некретнинама';
            contracts.textContent = 'Уговори о некретнинама, предуговори и регистрације';
            estate.textContent = 'Реструктурирање некретнина и усклађеност са прописима';
            communication.textContent = 'Комуникација са катастром и државним органима';
            resolution.textContent = 'Решавање спорова и парничење';
            mediation.textContent = 'Медијација пред Привредном комором';
            debt.textContent = 'Поступци извршења и наплата дуга';
            civil.textContent = 'Заступање у грађанским, кривичним и извршним поступцима';
            return;
        default:
            legalServices.textContent = 'Правне услуге';
            corporateTitle.textContent = 'Корпоративно и пословно право';
            legalSupport.textContent = 'Правна подршка током редовних пословних активности';
            compliance.textContent = 'Усклађеност са српским пореским законима и регистрација предузећа';
            drafting.textContent = 'Израда уговора и управљање акционарским споразумима';
            loan.textContent = 'Уговори о зајму, закупу и купопродаји';
            immigrationTitle.textContent = 'Закон о имиграцији и држављанству';
            visa.textContent = 'Захтеви за визе, радне дозволе и поступци за добијање држављанства';
            paperwork.textContent = 'Комплетна папирологија и правно извршење';
            taxTitle.textContent = 'Пореско и финансијско право';
            taxation.textContent = 'Саветовање о двоструком опорезивању, пореским одбитцима';
            obligation.textContent = 'Потврде о измиреним пореским обавезама';
            authorities.textContent = 'Заступање пред пореским органима';
            realEstate.textContent = 'Закон о некретнинама';
            contracts.textContent = 'Уговори о некретнинама, предуговори и регистрације';
            estate.textContent = 'Реструктурирање некретнина и усклађеност са прописима';
            communication.textContent = 'Комуникација са катастром и државним органима';
            resolution.textContent = 'Решавање спорова и парничење';
            mediation.textContent = 'Медијација пред Привредном комором';
            debt.textContent = 'Поступци извршења и наплата дуга';
            civil.textContent = 'Заступање у грађанским, кривичним и извршним поступцима';
            return;
    }
}